name: CI/CD Pipeline for Firebase App Distribution

on:
  push:
    branches:
      - master  # Trigger the pipeline when code is pushed to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger the pipeline on pull requests to 'master'

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu environment to run the job

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from GitHub

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.24.5  # Use the stable version of Flutter
    
    # Step 3: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Use Eclipse Temurin JDK distribution
        java-version: '17'  # Use Java 17
        
    # Step 4: Install Android dependencies
    - name: Set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        sudo apt-get install -y unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk-linux
        yes | $HOME/android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk-linux --licenses
        $HOME/android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk-linux "platform-tools" "build-tools;30.0.3" "platforms;android-30"  # You can specify the build tools and platform you want to use

    # Step 5: Install Flutter dependencies
    - name: Install dependencies
      run: flutter pub get  # Install the dependencies specified in pubspec.yaml

    # Step 6: Build the APK in release mode
    - name: Build APK
      run: flutter build apk --release  # Build the APK for release

    # Step 7: Install Firebase CLI
    - name: Install Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash  # Install the Firebase CLI globally
    
    # Step 8: Upload to Firebase App Distribution
    - name: Upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: "1:831812078730:android:7585733fa65a386339b173"
        token: ${{ secrets.FIREBASE_TOKEN }}
        testers: roaa20102002@gmail.com,shroukheshmat0@gmail.com
        file: build/app/outputs/flutter-apk/app-release.apk
